### ISSUE TITLE
Version retrieval logic does not work for applications run from installed gem

### ISSUE THREAD

**Issue by dmitryfleytman** [mpalmer/git-version-bump#13]
The problem is that such an applications require all their files via require_relative or require with full path, so application gem never gets to the list of loaded gems returned by Gem.loaded_specs.

**Comment by mpalmer** [comment]
I *think* I understand what you're saying, but would you be able to quickly whip up a minimal test gem that demonstrates what's going on?  I have a funny feeling I'll end up spending a lot of time doing things slightly differently to what you're doing, and not actually hit the bug you're seeing.

**Comment by dmitryfleytman** [comment]
[simple-cli-gem.tar.gz](https://github.com/mpalmer/git-version-bump/files/874777/simple-cli-gem.tar.gz)

Here you go.
See test.sh inside for the steps to reproduce.

**Comment by mpalmer** [comment]
Awesome, thanks for that.  This'll greatly help me nail the right bug.

**Comment by mpalmer** [comment]
This got fixed as part of the fix for #22, I believe.  The symptoms are very similar, and I can repro with an older gvb but can't with the latest version.
